# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chou/Documents/M1/ProgrammationParralleleC++/Devoir

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chou/Documents/M1/ProgrammationParralleleC++/Devoir

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chou/Documents/M1/ProgrammationParralleleC++/Devoir/CMakeFiles /home/chou/Documents/M1/ProgrammationParralleleC++/Devoir/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chou/Documents/M1/ProgrammationParralleleC++/Devoir/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named grenouilloland

# Build rule for target.
grenouilloland: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grenouilloland
.PHONY : grenouilloland

# fast build rule for target.
grenouilloland/fast:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/build
.PHONY : grenouilloland/fast

src/Modele/Case.o: src/Modele/Case.cpp.o

.PHONY : src/Modele/Case.o

# target to build an object file
src/Modele/Case.cpp.o:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/Case.cpp.o
.PHONY : src/Modele/Case.cpp.o

src/Modele/Case.i: src/Modele/Case.cpp.i

.PHONY : src/Modele/Case.i

# target to preprocess a source file
src/Modele/Case.cpp.i:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/Case.cpp.i
.PHONY : src/Modele/Case.cpp.i

src/Modele/Case.s: src/Modele/Case.cpp.s

.PHONY : src/Modele/Case.s

# target to generate assembly for a file
src/Modele/Case.cpp.s:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/Case.cpp.s
.PHONY : src/Modele/Case.cpp.s

src/Modele/Coordonnee.o: src/Modele/Coordonnee.cpp.o

.PHONY : src/Modele/Coordonnee.o

# target to build an object file
src/Modele/Coordonnee.cpp.o:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/Coordonnee.cpp.o
.PHONY : src/Modele/Coordonnee.cpp.o

src/Modele/Coordonnee.i: src/Modele/Coordonnee.cpp.i

.PHONY : src/Modele/Coordonnee.i

# target to preprocess a source file
src/Modele/Coordonnee.cpp.i:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/Coordonnee.cpp.i
.PHONY : src/Modele/Coordonnee.cpp.i

src/Modele/Coordonnee.s: src/Modele/Coordonnee.cpp.s

.PHONY : src/Modele/Coordonnee.s

# target to generate assembly for a file
src/Modele/Coordonnee.cpp.s:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/Coordonnee.cpp.s
.PHONY : src/Modele/Coordonnee.cpp.s

src/Modele/Eau.o: src/Modele/Eau.cpp.o

.PHONY : src/Modele/Eau.o

# target to build an object file
src/Modele/Eau.cpp.o:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/Eau.cpp.o
.PHONY : src/Modele/Eau.cpp.o

src/Modele/Eau.i: src/Modele/Eau.cpp.i

.PHONY : src/Modele/Eau.i

# target to preprocess a source file
src/Modele/Eau.cpp.i:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/Eau.cpp.i
.PHONY : src/Modele/Eau.cpp.i

src/Modele/Eau.s: src/Modele/Eau.cpp.s

.PHONY : src/Modele/Eau.s

# target to generate assembly for a file
src/Modele/Eau.cpp.s:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/Eau.cpp.s
.PHONY : src/Modele/Eau.cpp.s

src/Modele/Grenouille.o: src/Modele/Grenouille.cpp.o

.PHONY : src/Modele/Grenouille.o

# target to build an object file
src/Modele/Grenouille.cpp.o:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/Grenouille.cpp.o
.PHONY : src/Modele/Grenouille.cpp.o

src/Modele/Grenouille.i: src/Modele/Grenouille.cpp.i

.PHONY : src/Modele/Grenouille.i

# target to preprocess a source file
src/Modele/Grenouille.cpp.i:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/Grenouille.cpp.i
.PHONY : src/Modele/Grenouille.cpp.i

src/Modele/Grenouille.s: src/Modele/Grenouille.cpp.s

.PHONY : src/Modele/Grenouille.s

# target to generate assembly for a file
src/Modele/Grenouille.cpp.s:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/Grenouille.cpp.s
.PHONY : src/Modele/Grenouille.cpp.s

src/Modele/Jeu.o: src/Modele/Jeu.cpp.o

.PHONY : src/Modele/Jeu.o

# target to build an object file
src/Modele/Jeu.cpp.o:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/Jeu.cpp.o
.PHONY : src/Modele/Jeu.cpp.o

src/Modele/Jeu.i: src/Modele/Jeu.cpp.i

.PHONY : src/Modele/Jeu.i

# target to preprocess a source file
src/Modele/Jeu.cpp.i:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/Jeu.cpp.i
.PHONY : src/Modele/Jeu.cpp.i

src/Modele/Jeu.s: src/Modele/Jeu.cpp.s

.PHONY : src/Modele/Jeu.s

# target to generate assembly for a file
src/Modele/Jeu.cpp.s:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/Jeu.cpp.s
.PHONY : src/Modele/Jeu.cpp.s

src/Modele/SNenuphardDopant.o: src/Modele/SNenuphardDopant.cpp.o

.PHONY : src/Modele/SNenuphardDopant.o

# target to build an object file
src/Modele/SNenuphardDopant.cpp.o:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/SNenuphardDopant.cpp.o
.PHONY : src/Modele/SNenuphardDopant.cpp.o

src/Modele/SNenuphardDopant.i: src/Modele/SNenuphardDopant.cpp.i

.PHONY : src/Modele/SNenuphardDopant.i

# target to preprocess a source file
src/Modele/SNenuphardDopant.cpp.i:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/SNenuphardDopant.cpp.i
.PHONY : src/Modele/SNenuphardDopant.cpp.i

src/Modele/SNenuphardDopant.s: src/Modele/SNenuphardDopant.cpp.s

.PHONY : src/Modele/SNenuphardDopant.s

# target to generate assembly for a file
src/Modele/SNenuphardDopant.cpp.s:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/SNenuphardDopant.cpp.s
.PHONY : src/Modele/SNenuphardDopant.cpp.s

src/Modele/SNenuphardImmortel.o: src/Modele/SNenuphardImmortel.cpp.o

.PHONY : src/Modele/SNenuphardImmortel.o

# target to build an object file
src/Modele/SNenuphardImmortel.cpp.o:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/SNenuphardImmortel.cpp.o
.PHONY : src/Modele/SNenuphardImmortel.cpp.o

src/Modele/SNenuphardImmortel.i: src/Modele/SNenuphardImmortel.cpp.i

.PHONY : src/Modele/SNenuphardImmortel.i

# target to preprocess a source file
src/Modele/SNenuphardImmortel.cpp.i:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/SNenuphardImmortel.cpp.i
.PHONY : src/Modele/SNenuphardImmortel.cpp.i

src/Modele/SNenuphardImmortel.s: src/Modele/SNenuphardImmortel.cpp.s

.PHONY : src/Modele/SNenuphardImmortel.s

# target to generate assembly for a file
src/Modele/SNenuphardImmortel.cpp.s:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/SNenuphardImmortel.cpp.s
.PHONY : src/Modele/SNenuphardImmortel.cpp.s

src/Modele/SNenuphardMortel.o: src/Modele/SNenuphardMortel.cpp.o

.PHONY : src/Modele/SNenuphardMortel.o

# target to build an object file
src/Modele/SNenuphardMortel.cpp.o:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/SNenuphardMortel.cpp.o
.PHONY : src/Modele/SNenuphardMortel.cpp.o

src/Modele/SNenuphardMortel.i: src/Modele/SNenuphardMortel.cpp.i

.PHONY : src/Modele/SNenuphardMortel.i

# target to preprocess a source file
src/Modele/SNenuphardMortel.cpp.i:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/SNenuphardMortel.cpp.i
.PHONY : src/Modele/SNenuphardMortel.cpp.i

src/Modele/SNenuphardMortel.s: src/Modele/SNenuphardMortel.cpp.s

.PHONY : src/Modele/SNenuphardMortel.s

# target to generate assembly for a file
src/Modele/SNenuphardMortel.cpp.s:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/SNenuphardMortel.cpp.s
.PHONY : src/Modele/SNenuphardMortel.cpp.s

src/Modele/SNenuphardNormal.o: src/Modele/SNenuphardNormal.cpp.o

.PHONY : src/Modele/SNenuphardNormal.o

# target to build an object file
src/Modele/SNenuphardNormal.cpp.o:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/SNenuphardNormal.cpp.o
.PHONY : src/Modele/SNenuphardNormal.cpp.o

src/Modele/SNenuphardNormal.i: src/Modele/SNenuphardNormal.cpp.i

.PHONY : src/Modele/SNenuphardNormal.i

# target to preprocess a source file
src/Modele/SNenuphardNormal.cpp.i:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/SNenuphardNormal.cpp.i
.PHONY : src/Modele/SNenuphardNormal.cpp.i

src/Modele/SNenuphardNormal.s: src/Modele/SNenuphardNormal.cpp.s

.PHONY : src/Modele/SNenuphardNormal.s

# target to generate assembly for a file
src/Modele/SNenuphardNormal.cpp.s:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/SNenuphardNormal.cpp.s
.PHONY : src/Modele/SNenuphardNormal.cpp.s

src/Modele/SNenuphardNutritif.o: src/Modele/SNenuphardNutritif.cpp.o

.PHONY : src/Modele/SNenuphardNutritif.o

# target to build an object file
src/Modele/SNenuphardNutritif.cpp.o:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/SNenuphardNutritif.cpp.o
.PHONY : src/Modele/SNenuphardNutritif.cpp.o

src/Modele/SNenuphardNutritif.i: src/Modele/SNenuphardNutritif.cpp.i

.PHONY : src/Modele/SNenuphardNutritif.i

# target to preprocess a source file
src/Modele/SNenuphardNutritif.cpp.i:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/SNenuphardNutritif.cpp.i
.PHONY : src/Modele/SNenuphardNutritif.cpp.i

src/Modele/SNenuphardNutritif.s: src/Modele/SNenuphardNutritif.cpp.s

.PHONY : src/Modele/SNenuphardNutritif.s

# target to generate assembly for a file
src/Modele/SNenuphardNutritif.cpp.s:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/SNenuphardNutritif.cpp.s
.PHONY : src/Modele/SNenuphardNutritif.cpp.s

src/Modele/SNenuphardVeneneux.o: src/Modele/SNenuphardVeneneux.cpp.o

.PHONY : src/Modele/SNenuphardVeneneux.o

# target to build an object file
src/Modele/SNenuphardVeneneux.cpp.o:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/SNenuphardVeneneux.cpp.o
.PHONY : src/Modele/SNenuphardVeneneux.cpp.o

src/Modele/SNenuphardVeneneux.i: src/Modele/SNenuphardVeneneux.cpp.i

.PHONY : src/Modele/SNenuphardVeneneux.i

# target to preprocess a source file
src/Modele/SNenuphardVeneneux.cpp.i:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/SNenuphardVeneneux.cpp.i
.PHONY : src/Modele/SNenuphardVeneneux.cpp.i

src/Modele/SNenuphardVeneneux.s: src/Modele/SNenuphardVeneneux.cpp.s

.PHONY : src/Modele/SNenuphardVeneneux.s

# target to generate assembly for a file
src/Modele/SNenuphardVeneneux.cpp.s:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/SNenuphardVeneneux.cpp.s
.PHONY : src/Modele/SNenuphardVeneneux.cpp.s

src/Modele/grenouilloland.o: src/Modele/grenouilloland.cpp.o

.PHONY : src/Modele/grenouilloland.o

# target to build an object file
src/Modele/grenouilloland.cpp.o:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/grenouilloland.cpp.o
.PHONY : src/Modele/grenouilloland.cpp.o

src/Modele/grenouilloland.i: src/Modele/grenouilloland.cpp.i

.PHONY : src/Modele/grenouilloland.i

# target to preprocess a source file
src/Modele/grenouilloland.cpp.i:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/grenouilloland.cpp.i
.PHONY : src/Modele/grenouilloland.cpp.i

src/Modele/grenouilloland.s: src/Modele/grenouilloland.cpp.s

.PHONY : src/Modele/grenouilloland.s

# target to generate assembly for a file
src/Modele/grenouilloland.cpp.s:
	$(MAKE) -f CMakeFiles/grenouilloland.dir/build.make CMakeFiles/grenouilloland.dir/src/Modele/grenouilloland.cpp.s
.PHONY : src/Modele/grenouilloland.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... grenouilloland"
	@echo "... src/Modele/Case.o"
	@echo "... src/Modele/Case.i"
	@echo "... src/Modele/Case.s"
	@echo "... src/Modele/Coordonnee.o"
	@echo "... src/Modele/Coordonnee.i"
	@echo "... src/Modele/Coordonnee.s"
	@echo "... src/Modele/Eau.o"
	@echo "... src/Modele/Eau.i"
	@echo "... src/Modele/Eau.s"
	@echo "... src/Modele/Grenouille.o"
	@echo "... src/Modele/Grenouille.i"
	@echo "... src/Modele/Grenouille.s"
	@echo "... src/Modele/Jeu.o"
	@echo "... src/Modele/Jeu.i"
	@echo "... src/Modele/Jeu.s"
	@echo "... src/Modele/SNenuphardDopant.o"
	@echo "... src/Modele/SNenuphardDopant.i"
	@echo "... src/Modele/SNenuphardDopant.s"
	@echo "... src/Modele/SNenuphardImmortel.o"
	@echo "... src/Modele/SNenuphardImmortel.i"
	@echo "... src/Modele/SNenuphardImmortel.s"
	@echo "... src/Modele/SNenuphardMortel.o"
	@echo "... src/Modele/SNenuphardMortel.i"
	@echo "... src/Modele/SNenuphardMortel.s"
	@echo "... src/Modele/SNenuphardNormal.o"
	@echo "... src/Modele/SNenuphardNormal.i"
	@echo "... src/Modele/SNenuphardNormal.s"
	@echo "... src/Modele/SNenuphardNutritif.o"
	@echo "... src/Modele/SNenuphardNutritif.i"
	@echo "... src/Modele/SNenuphardNutritif.s"
	@echo "... src/Modele/SNenuphardVeneneux.o"
	@echo "... src/Modele/SNenuphardVeneneux.i"
	@echo "... src/Modele/SNenuphardVeneneux.s"
	@echo "... src/Modele/grenouilloland.o"
	@echo "... src/Modele/grenouilloland.i"
	@echo "... src/Modele/grenouilloland.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

